#!/usr/bin/env bash

idnumber=$(echo $(wget -q https://www.olivevideoeditor.org/nightly.php -O -) | sed 's/zuluTime/\n/g' | head -2 | tr " " "\n" | grep href | tail -1 | cut -c 13- | rev | cut -c 2- | rev)
wget https://github.com/srevinsaju/Firefox-Appimage/releases/download/firefox-v98.0.r20220322144853/firefox-98.0.r20220322144853-x86_64.AppImage -O downloader
mkdir downloader.home
chmod a+x ./downloader
timeout 60s ./downloader -headless https://www.olivevideoeditor.org/go?id=$idnumber
unzip ./downloader.home/Downloads/*.zip
if test -t ./downloader.home/Downloads/*AppImage
then
	mv downloader.home/Downloads/*AppImage .
fi
